# Generated by Erlang.mk. Edit at your own risk!

src/core3_lumix_sup.erl:: include/rtrace.hrl; @touch $@
src/lumix_actions.erl:: include/common.hrl include/rtrace.hrl include/zigBeeDEF.hrl; @touch $@
src/lumix_multiplex.erl:: include/common.hrl include/rtrace.hrl include/zigBeeDEF.hrl; @touch $@
src/lumix_utils.erl:: include/common.hrl include/rtrace.hrl; @touch $@

COMPILE_FIRST +=
